### ISSUE TITLE
Bonjour, est-ce que vous avez le code souce de disk2vhd 

### ISSUE THREAD

**Issue by stlcours** [wooxo/Vhd2Disk#1]
L'outil de disk2vhd pour télécharger:
https://technet.microsoft.com/en-us/sysinternals/ee656415

Ou vous avez des idées pour réaliser cette fonctionalité? Merci.
Cordialement
Stlcours

**Comment by orkblutt** [comment]
Bonjour stlcours,

Le principe est exactement le même que vhd2disk mais à l'envers. Il faut utiliser VSS pour pouvoir lire le volume dans un état cohérent et "figé".
Dans quel but voudriez vous avoir accès au code source de Disk2Vhd ?

Cordialement,

Bruno Roques
