### ISSUE TITLE
Binary release

### ISSUE THREAD

**Issue by thany** [wooxo/Vhd2Disk#2]
Can you make a binary release, please?

**Comment by ThomasCr** [comment]
Take a look at https://qa.social.technet.microsoft.com/Forums/sqlserver/en-US/3a16ede5-6deb-4f63-936a-991c484b73f6/vhd2disk?forum=disk2vhd

**Comment by Zero3K** [comment]
I think the binaries you linked to in that post should be uploaded to the Releases page of its repository so they won't be lost as easily and they'll also be easier to get to.

**Comment by orkblutt** [comment]
Here a x64 release: https://github.com/wooxo/Vhd2Disk/releases

**Comment by Zero3K** [comment]
Please also make a 32-bit version or put the one you made earlier on that page. Thanks.

**Comment by orkblutt** [comment]
Done.
