### ISSUE TITLE
Fix the issues with VHDTool or include its functionality

### ISSUE THREAD

**Issue by Zero3K** [wooxo/Vhd2Disk#7]
It would be nice if you could fix the issues with VHDTool or included its functionality into Vhd2Disk. VHDTool's issues are at https://github.com/TobiasFaller/VHDTool/issues.

**Comment by MegaZeroX10** [comment]
Never mind, the developer of it has done some things in its repository which makes me think that it should have a new version available soon,

**Comment by Zero3K** [comment]
Never mind, the developer of it has done some things in its repository which makes me think that it should have a new version available soon,
